port: 8080
kafka:
  brokers: localhost:9092
  client_id: observer-producer
  log_topic: observer-logs
  bootstrap_topics:
    - observer-producer
    - observer-logs
    - mutates
  mutate_topic: mutates
  log_chan_size: 1000
  mutate_chan_size: 1000
storage:
  port: 8082
  wal_path: data.wal